pipeline{
    agent any 
    stages{
        stage('Checkout'){
            steps{
                git 'https://github.com/nguyec-baokhang/template-app.git'
            }
        }
        stage('Build'){
            steps{
                sh '''
                    docker build -t template_app . 
                '''
            }
        }
        stage('Run'){
            steps{
                sh'''
                    docker run -d template_app -p 8000:8000
                '''
            }
        }
    }
}